import { flagged } from '@/server/graph/access';
import { withApi } from '@/server/http/api';
import { AppError } from '@/server/http/errors';
import { STATS_READ_LIMIT } from '@/server/stats/http';
import { getRun } from '@/server/stats/runs';

type Params = { projectId: string; runId: string; figureId: string };

/** A figure's SVG. Generated by the engine from stored estimates; served inert (no scripts, no external loads). */
export const GET = flagged(
  withApi<undefined, Params>({ rateLimit: STATS_READ_LIMIT }, async ({ user, params }) => {
    const { figures } = await getRun({ userId: user.id }, params.runId, params.projectId);
    const figure = figures.find((entry) => entry.id === params.figureId);
    if (!figure) throw new AppError('NOT_FOUND', 'The figure was not found.', 'لم يُعثر على الشكل.');
    return new Response(figure.svg, {
      headers: {
        'content-type': 'image/svg+xml; charset=utf-8',
        'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'",
        'x-content-type-options': 'nosniff',
        'cache-control': 'private, max-age=31536000, immutable',
      },
    });
  }),
);
